### ISSUE TITLE
What happens if I guess correctly vs incorrectly

### ISSUE THREAD

**Issue by JazzyEngineer** [pridgey/connections.pridgey.dev#2]
Tell people that the choices will change color if you're right, counter will progress with every guess.

Example from Wordle (color tiles won't copy and paste here, but can be seen [here](https://www.nytimes.com/games/wordle/index.html)): 

After each guess, the color of the tiles will change to show how close your guess was to the word.

Examples

    
The letter W is in the word and in the correct spot.

    
The letter I is in the word but in the wrong spot.

    
The letter U is not in the word in any spot.

**Comment by pridgey** [comment]
Latest release includes visual feedback that your guess was incorrect.

Keeping this issue open to think on adding clues, which seems to be the heart of this issue.

**Comment by pridgey** [comment]
Giving this more thought, and I think that providing hints doesn't quite work well in this style of game and goes against the style of gameplay. It makes sense for something like Wordle, but barring any kind of overwhelming feedback I'm going to leave it out of this game.
